repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/python/black
    rev: 21.12b0
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      pass_filenames: true
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    - id: pyupgrade
      args: ["--py37-plus", "--keep-runtime-typing"]